feedback/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import welcome

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('userform.urls')),
    url(r'^', include('registerapp.urls')),
    url(r'^', include('mapreceive.urls')),

]

mapreceive/models.py
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from feedback import settings
from django.contrib.postgres import fields
from django.db.models import Q
import datetime
import psycopg2

_CHOICE_GENDER = (('F','Female'),('M','Male'))
_CHOICE_TPL = (('Y','Yes'),('N','No'))
RATING_CHOICES = ((0, 'Never used'),(1, 'Bad'),(2, 'Below Average'),(3, 'Average'),(4, 'Above Average'),(5, 'Good'))
_DIST_LIST = (('Mirpur', 'Mirpur'),('Khairpur', 'Khairpur'),('Shikarpur', 'Shikarpur'),('Hyderabad', 'Hyderabad'),('Karachi', 'Karachi'))
_ACTIVITY_LIST = (('Activity_1','Activity_1'),('Activity_2','Activity_2'),('Activity_3','Activity_3'),('Activity_4','Activity_4'))
_TALUKA_LIST = (('Taluka-1', 'Taluka-1'),('Taluka-2', 'Taluka-2'),('Taluka-3', 'Taluka-3'),('Taluka-4', 'Taluka-4'),('Taluka-5', 'Taluka-5'))
_UC_LIST = (('UC-1', 'UC-1'),('UC-2', 'UC-2'),('UC-3', 'UC-3'),('UC-4', 'UC-4'),('UC-5', 'UC-5'))


class MapReceiveQuerySet(models.QuerySet):
    def all_mapreceive(self):
        return self.all()

class MapReceive(models.Model):
    def getLookupValue(self,type):
        #print(settings.DATABASES)
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']
        try:
            conn = psycopg2.connect(database=dbname,
                                    user=username,host=host,
                                    password=password,port=port)
            #conn.set_isolation_level(ISOLEVEL)
            cursor = conn.cursor()
            if(type=='dist'):
                cursor.execute("select district,district from lookup group by district order by district")
            elif(type=='tehs'):
                cursor.execute("select tehsil,tehsil from lookup group by tehsil order by tehsil")
            elif(type=='uc'):
                cursor.execute("select uc,uc from lookup group by uc order by uc")
            fetch = cursor.fetchall()

            #dblist = [fetch[i][0] for i in range(len(fetch))]
            lookuplist = []
            for i in range(len(fetch)):
                lookuplist.append((fetch[i][1], fetch[i][0]))
            print('hello world')
        except psycopg2.Error as e:
            print(e)
        finally:
            conn.close()
        #dist_list = (('Hyderabad', 'Hyderabad'),('Karachi', 'Karachi'))
        return lookuplist

    from_user = models.CharField(max_length=30, null=False)

    sop_no = models.CharField(max_length=30,default="00-00",verbose_name="SOP No.")
    map_date = models.DateField(blank=True,default=datetime.datetime.now, verbose_name="Map Receiving Date")
    #activity = models.CharField(max_length=30,default="Activity_1",choices=_ACTIVITY_LIST,verbose_name="Choose Activity")
    dist = models.CharField(max_length=30,default="Karachi", choices=getLookupValue('lookup','dist'), verbose_name="District")
    taluka = models.CharField(max_length=30,default="Taluka-1", choices=getLookupValue('lookup','tehs'), verbose_name="Taluka")
    uc = models.CharField(max_length=30,default="UC-1", choices=getLookupValue('lookup','uc'), verbose_name="Union Council")

    from_office = models.CharField(max_length=30, default="", verbose_name="From")
    to_office = models.CharField(max_length=30 , default="", verbose_name="To")

    map_name_1 = models.CharField(max_length=30, default="",verbose_name="1. Map Name")
    serial_from_1 = models.IntegerField(default='0',verbose_name="1. Serial No. (From)")
    serial_to_1 = models.IntegerField(default='0', verbose_name="1. Serial No. (To)")
    copies_1 = models.IntegerField(default='0',verbose_name="1. Copies")
    quantity_1 = models.IntegerField(default='0',verbose_name="1. Quantity")
    remarks_1 = models.CharField(max_length=30, default="",verbose_name="1. Remarks")

    map_name_2 = models.CharField(max_length=30, default="", verbose_name="2. Map Name")
    serial_from_2 = models.IntegerField(default='0', verbose_name="2. Serial No. (From)")
    serial_to_2 = models.IntegerField(default='0', verbose_name="2. Serial No. (To)")
    copies_2 = models.IntegerField(default='0', verbose_name="2. Copies")
    quantity_2 = models.IntegerField(default='0', verbose_name="2. Quantity")
    remarks_2 = models.CharField(max_length=30, default="", verbose_name="2. Remarks")

    map_name_3 = models.CharField(max_length=30, default="", verbose_name="3. Map Name")
    serial_from_3 = models.IntegerField(default='0', verbose_name="3. Serial No. (From)")
    serial_to_3 = models.IntegerField(default='0', verbose_name="3. Serial No. (To)")
    copies_3 = models.IntegerField(default='0', verbose_name="3. Copies")
    quantity_3 = models.IntegerField(default='0', verbose_name="3. Quantity")
    remarks_3 = models.CharField(max_length=30, default="", verbose_name="3. Remarks")

    map_name_4 = models.CharField(max_length=30, default="", verbose_name="4. Map Name")
    serial_from_4 = models.IntegerField(default='0', verbose_name="4. Serial No. (From)")
    serial_to_4 = models.IntegerField(default='0', verbose_name="4. Serial No. (To)")
    copies_4 = models.IntegerField(default='0', verbose_name="4. Copies")
    quantity_4 = models.IntegerField(default='0', verbose_name="4. Quantity")
    remarks_4 = models.CharField(max_length=30, default="", verbose_name="4. Remarks")

    map_name_5 = models.CharField(max_length=30, default="", verbose_name="5. Map Name")
    serial_from_5 = models.IntegerField(default='0', verbose_name="5. Serial No. (From)")
    serial_to_5 = models.IntegerField(default='0', verbose_name="5. Serial No. (To)")
    copies_5 = models.IntegerField(default='0', verbose_name="5. Copies")
    quantity_5 = models.IntegerField(default='0', verbose_name="5. Quantity")
    remarks_5 = models.CharField(max_length=30, default="", verbose_name="5. Remarks")

    map_name_6 = models.CharField(max_length=30, default="", verbose_name="6. Map Name")
    serial_from_6 = models.IntegerField(default='0', verbose_name="6. Serial No. (From)")
    serial_to_6 = models.IntegerField(default='0', verbose_name="6. Serial No. (To)")
    copies_6 = models.IntegerField(default='0', verbose_name="6. Copies")
    quantity_6 = models.IntegerField(default='0', verbose_name="6. Quantity")
    remarks_6 = models.CharField(max_length=30, default="", verbose_name="6. Remarks")

    handed_over_name = models.CharField(max_length=30, default="", null=False, verbose_name="Handed Over Name")
    handed_over_desig = models.CharField(max_length=30, default="",null=False,verbose_name="Handed Over Designation")
    handed_over_date = models.DateField(blank=True,default=datetime.datetime.now,verbose_name="Handed Over Date")

    taken_over_name = models.CharField(max_length=30, default="", null=False, verbose_name="Taken Over Name")
    taken_over_desig = models.CharField(max_length=30, default="", null=False, verbose_name="Taken Over Designation")
    taken_over_date = models.DateField(blank=True,default=datetime.datetime.now, verbose_name="Taken Over Date")
    objects = MapReceiveQuerySet.as_manager()

userform/forms.py
from django.forms import ModelForm, DateInput
from .models import Feedback, FeedbackMeta, Surveyors, TeamLeads
from django import forms
from feedback import settings
import psycopg2
class FeedbackForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(FeedbackForm, self).__init__(*args, **kwargs)
        self.fields["activity"].choices= self.get_Activities()
        self.fields["Surveyor"].choices = self.getSurveyorsLookup()
        self.fields["TeamLeads"].choices = self.getTeamLeadsLookup()

        for key in self.fields:
            self.fields[key].required = True
    def getTeamLeadsLookup(self):
        #print(settings.DATABASES)
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']
        conn = psycopg2.connect(database=dbname,
                                user=username,host=host,
                                password=password,port=port)
        #conn.set_isolation_level(ISOLEVEL)
        cursor = conn.cursor()
        cursor.execute('select "TL_Name","TL_Name" from userform_teamleads order by "TL_Name"')
        fetch = cursor.fetchall()

        lookuplist = []
        for i in range(len(fetch)):
            lookuplist.append((fetch[i][1], fetch[i][0]))
        conn.close()
        return lookuplist


    def getSurveyorsLookup(self):
        #print(settings.DATABASES)
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']
        conn = psycopg2.connect(database=dbname,
                                user=username,host=host,
                                password=password,port=port)
        #conn.set_isolation_level(ISOLEVEL)
        cursor = conn.cursor()
        cursor.execute('select "Sur_Name","Sur_Name" from userform_surveyors order by "Sur_Name"')
        fetch = cursor.fetchall()

        lookuplist = []
        for i in range(len(fetch)):
            lookuplist.append((fetch[i][1], fetch[i][0]))
        conn.close()
        return lookuplist

    def get_Activities(self):
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']

        conn = psycopg2.connect(database=dbname,
                                user=username,host=host,
                                password=password,port=port)

        cursor = conn.cursor()
        cursor.execute("select activity,activity from userform_feedbackmeta order by activity")

        fetch= cursor.fetchall()
        lookuplist = []
        for i in range(len(fetch)):
            lookuplist.append((fetch[i][1], fetch[i][0]))
        return lookuplist

    activity= forms.ChoiceField(choices=get_Activities('lookup'),)
    Surveyor = forms.ChoiceField(choices=getSurveyorsLookup('lookup'), )
    TeamLeads = forms.ChoiceField(choices=getTeamLeadsLookup('lookup'), )


    class Meta:
        model = Feedback

        widgets = {
            'visit_date': DateInput(attrs={'type': 'date'})
        }

        exclude = ['time','from_user',]


class AddUcsMeta(forms.Form):
    division_name = forms.CharField(max_length=60)
    District_Name = forms.CharField(max_length=60)
    Taluka_Name= forms.CharField(max_length=60)
    Union_Councile_Name= forms.CharField(max_length=60)
    Low_Priority = forms.BooleanField()




class FeedbackFormMeta(ModelForm):
    def __init__(self, *args, **kwargs):
        super(FeedbackFormMeta, self).__init__(*args, **kwargs)
        self.fields["Surveyors"].choices = self.getSurveyorsLookup()
        self.fields["TeamLeads"].choices = self.getTeamLeadsLookup()
        for key in self.fields:
            self.fields[key].required = True

    def getTeamLeadsLookup(self):
        #print(settings.DATABASES)
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']
        conn = psycopg2.connect(database=dbname,
                                user=username,host=host,
                                password=password,port=port)
        #conn.set_isolation_level(ISOLEVEL)
        cursor = conn.cursor()
        cursor.execute('select "TL_Name","TL_Name" from userform_teamleads order by "TL_Name"')
        fetch = cursor.fetchall()

        lookuplist = []
        for i in range(len(fetch)):
            lookuplist.append((fetch[i][1], fetch[i][0]))
        conn.close()
        return lookuplist


    def getSurveyorsLookup(self):
        #print(settings.DATABASES)
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']
        conn = psycopg2.connect(database=dbname,
                                user=username,host=host,
                                password=password,port=port)
        #conn.set_isolation_level(ISOLEVEL)
        cursor = conn.cursor()
        cursor.execute('select "Sur_Name","Sur_Name" from userform_surveyors order by "Sur_Name"')
        fetch = cursor.fetchall()

        lookuplist = []
        for i in range(len(fetch)):
            lookuplist.append((fetch[i][1], fetch[i][0]))
        conn.close()
        return lookuplist

    def getLookupValue(self,type):
        #print(settings.DATABASES)
        dbname = settings.DATABASES['default']['NAME']
        username = settings.DATABASES['default']['USER']
        password = settings.DATABASES['default']['PASSWORD']
        host = settings.DATABASES['default']['HOST']
        port = settings.DATABASES['default']['PORT']
        try:
            conn = psycopg2.connect(database=dbname,
                                    user=username,host=host,
                                    password=password,port=port)
            #conn.set_isolation_level(ISOLEVEL)
            cursor = conn.cursor()
            if(type=='dist'):
                cursor.execute("select district,district from lookup group by district order by district")
            elif(type=='tehs'):
                cursor.execute("select tehsil,tehsil from lookup group by tehsil order by tehsil")
            elif(type=='uc'):
                cursor.execute("select uc,uc from lookup group by uc order by uc")
            fetch = cursor.fetchall()

            #dblist = [fetch[i][0] for i in range(len(fetch))]
            lookuplist = []
            for i in range(len(fetch)):
                lookuplist.append((fetch[i][1], fetch[i][0]))
            print('hello world')
        except psycopg2.Error as e:
            print(e)
        finally:
            conn.close()
        #dist_list = (('Hyderabad', 'Hyderabad'),('Karachi', 'Karachi'))
        return lookuplist

    OPTIONS = getLookupValue('lookup','uc')
    uc = forms.MultipleChoiceField(widget=forms.SelectMultiple,
                                   choices=OPTIONS)
    Surveyors = forms.MultipleChoiceField(widget=forms.SelectMultiple,
                                   choices=getSurveyorsLookup('lookup'))
    TeamLeads = forms.MultipleChoiceField(widget=forms.SelectMultiple,
                                   choices=getTeamLeadsLookup('lookup'))

    class Meta:
        model = FeedbackMeta
        widgets = {
            'visit_date': DateInput(attrs={'type': 'date'})
        }

        exclude= []



class SurveyorMetaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(SurveyorMetaForm, self).__init__(*args, **kwargs)
        for key in self.fields:
            self.fields[key].required = True
    class Meta:
        model = Surveyors
        widgets = {
            'Sur_Date': DateInput(attrs={'type': 'date'})
        }

        exclude= []

class TeamLeadsMetaForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(TeamLeadsMetaForm, self).__init__(*args, **kwargs)

        for key in self.fields:
            self.fields[key].required = True
    class Meta:
        model = TeamLeads
        widgets = {
            'TL_Date': DateInput(attrs={'type': 'date'})
        }

        exclude= []

feedback/views.py
from django.shortcuts import render, redirect

def welcome(request):
    if request.user.is_authenticated:
        return redirect('new_feedback')
    else:
        return render(request, 'tictac/welcome.html')

templates/feedback/addSurveyors.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}





   <div class="container">

        <div class="row">
            <div class="well class-sm-6">
                <form id="frm_add" class="form-group" role="form" action="{% url 'surveyor_handle' %}" method="POST">

                    {% csrf_token %}
                        <table class="table table-borderless">
                            {{  form.as_table  }}
                        </table>
                    <button type="submit">Submit</button>

                </form>
            </div>
        </div>
        <script>
        $(document).ready(function(){

           $("#frm_add").submit(function(){
                 alert("Thank you for your feedback")
                //e.preventDefault();

            });
        });
        </script>

     </div>


{% endblock content %}

templates/feedback/feedback_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}




    <div class="container">

        <div class="row">
            <div class="well class-sm-6">
                <form id="frm_add" class="form-group" role="form" action="{% url 'new_feedback' %}" method="POST">
                    {% csrf_token %}
                        <table class="table table-borderless">
                            {{  form.as_table  }}
                        </table>

                    <button type="submit">Submit</button>
                    <!--<input type="submit" value="Submit">-->
                </form>
            </div>
        </div>

        <script>
        $(document).ready(function(){

        $.ajax({
            url: '{% url "update_activities" %}',
            data: {
            },
            success: function (response) {
                var  str_array = response;
                $('#id_activity').empty();
                for(var i = 0; i < str_array.length; i++) {
                   //str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
                   $('#id_activity').append($('<option>', str_array[i]).text(str_array[i]))
                   //alert(str_array[i]);
                }

                  var act2 = $('#id_activity').val();

                    $.ajax({
                        url: '{% url "update_district" %}',
                        data: {
                            'activity': act2,
                        },
                        success: function (response) {
                            var  str_array = response;
                            $('#id_dist').empty();
            //                $('#id_taluka').empty();
             //               $('#id_uc').empty();
                            for(var i = 0; i < str_array.length; i++) {
                            $('#id_dist').append($('<option>', str_array[i]).text(str_array[i]))
                            }

                                        var act_feedback = $('#id_activity').val();
                                        var dist_feedback = $('#id_dist').val();

                                    $.ajax({
                                        url: '{% url "update_taluka_feedback" %}',
                                        data: {
                                            'activity': act_feedback,
                                            'district': dist_feedback,

                                        },
                                        success: function (response) {
                                            var  str_array = response;
                                            $('#id_taluka').empty();
                                            for(var i = 0; i < str_array.length; i++) {
                                            $('#id_taluka').append($('<option>', str_array[i]).text(str_array[i]))
                                            }


                                            //updating UCs
            var act_feedback = $('#id_activity').val();
            var dist_feedback = $('#id_dist').val();
            var taluk_feedback = $('#id_taluka').val();


        $.ajax({
            url: '{% url "update_uc_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,
                'taluka': dist_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_uc').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_uc').append($('<option>', str_array[i]).text(str_array[i]))
                }

            }
    });
//get surveyor's names
        $.ajax({
            url: '{% url "update_surveyors_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,
                'taluka': dist_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_Surveyor').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_Surveyor').append($('<option>', str_array[i]).text(str_array[i]))
                }

            }
    });

    // get team lead's names
        $.ajax({
            url: '{% url "update_teamleads_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,
                'taluka': dist_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_TeamLeads').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_TeamLeads').append($('<option>', str_array[i]).text(str_array[i]))
                }

            }
    });

                                        }
                                });

                        }
                });


            }
    });

// getting taluks from activity and district






            $("#frm_add").submit(function(){
                alert("Thank you for feedback !!!");

            });
        });
        </script>
{% block javascript %}
<script>

function change_feedback_activity()
{
            var act2 = $('#id_activity').val();

        $.ajax({
            url: '{% url "update_district" %}',
            data: {
                'activity': act2,
            },
            success: function (response) {
                var  str_array = response;
                $('#id_dist').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_dist').append($('<option>', str_array[i]).text(str_array[i]))
                }
                change_feedback_district()
            }
    });


}

function change_feedback_district()
{
            var act_feedback = $('#id_activity').val();
            var dist_feedback = $('#id_dist').val();

        $.ajax({
            url: '{% url "update_taluka_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_taluka').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_taluka').append($('<option>', str_array[i]).text(str_array[i]))
                }
                change_feedback_taluka();
                change_feedback_surveyors();
                change_feedback_teamleads();


            }
    });

}

function change_feedback_taluka()
{
            var act_feedback = $('#id_activity').val();
            var dist_feedback = $('#id_dist').val();
            var taluk_feedback = $('#id_taluka').val();

        $.ajax({
            url: '{% url "update_uc_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,
                'taluka': taluk_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_uc').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_uc').append($('<option>', str_array[i]).text(str_array[i]))
                }


            }
    });
}

function change_feedback_surveyors()
{
            var act_feedback = $('#id_activity').val();
            var dist_feedback = $('#id_dist').val();
            var taluk_feedback = $('#id_taluka').val();

        $.ajax({
            url: '{% url "update_surveyors_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,
                'taluka': taluk_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_Surveyor').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_Surveyor').append($('<option>', str_array[i]).text(str_array[i]))
                }

            }
    });

}

function change_feedback_teamleads()
{
            var act_feedback = $('#id_activity').val();
            var dist_feedback = $('#id_dist').val();
            var taluk_feedback = $('#id_taluka').val();

         $.ajax({
            url: '{% url "update_teamleads_feedback" %}',
            data: {
                'activity': act_feedback,
                'district': dist_feedback,
                'taluka': taluk_feedback,

            },
            success: function (response) {
                var  str_array = response;
                $('#id_TeamLeads').empty();
                for(var i = 0; i < str_array.length; i++) {
                $('#id_TeamLeads').append($('<option>', str_array[i]).text(str_array[i]))
                }

            }
    });
}





    $("#id_activity").change(function () {
    change_feedback_activity()
    });


    $("#id_dist").change(function () {
            change_feedback_district()


    });


     $("#id_taluka").change(function () {
        change_feedback_taluka()
    });




</script>
{% endblock %}
     </div>


{% endblock content %}

templates/feedback/feedback_meta.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}




    <div class="container">

        <div class="row">
            <div class="well class-sm-6">
                <form id="frm_add" class="form-group" role="form" action="{% url 'meta_feedback' %}" method="POST">
                <!--<form id="frm_add" class="form-group" role="form">-->
                    {% csrf_token %}
                        <table class="table table-borderless">
                            {{  form.as_table  }}
                        </table>
                    <button type="submit">Submit</button>
                    <!--<input type="submit" value="Submit">-->
                </form>
            </div>
        </div>

        <script>
        $(document).ready(function(){
        //submitting the form
          var frm = $('#frm_add');
            frm.submit(function () {
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                alert("Thank you for your Feedback")
            },
            error: function(data) {
                alert("Something went wrong! ")
            }
        });
        return false;
    });



        // when page is loaded
        var category2 = $('#id_dist').val();

        $.ajax({
            url: '{% url "update_taluka" %}',
            data: {
                'district': category2,
            },
            success: function (response) {
                var  str_array = response;
                $('#id_taluka').empty();
                for(var i = 0; i < str_array.length; i++) {
                   //str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
                   $('#id_taluka').append($('<option>', str_array[i]).text(str_array[i]))
                   //alert(str_array[i]);
                }

            }
    });

        var tehsil2 = $("#id_taluka").val();

        $.ajax({
            url: '{% url "update_uc" %}',
            data: {
                'tehsil': tehsil2,
            },
            success: function (response) {
                var  str_array = response;
                $('#id_uc').empty();
                for(var i = 0; i < str_array.length; i++) {
                   //str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
                   $('#id_uc').append($('<option>', str_array[i]).text(str_array[i]))
                   //alert(str_array[i]);
                }

            }
    });

/*            $("#frm_add").submit(function(){
                 alert("Thank you for your feedback")
                //e.preventDefault();

            }); */
        });
        </script>
{% block javascript %}
<script>

function update_meta_feedback_district()
{
        var category = $('#id_dist').val();

        $.ajax({
            url: '{% url "update_taluka" %}',
            data: {
                'district': category,
            },
            success: function (response) {
                var  str_array = response;
                $('#id_taluka').empty();
                for(var i = 0; i < str_array.length; i++) {
                   $('#id_taluka').append($('<option>', str_array[i]).text(str_array[i]))

                }
                update_meta_feedback_taluka()

            }
    });


}
function update_meta_feedback_taluka()
{
       var tehsil = $('#id_taluka').val();

        $.ajax({
            url: '{% url "update_uc" %}',
            data: {
                'tehsil': tehsil,
            },
            success: function (response) {
                var  str_array = response;
                $('#id_uc').empty();
                for(var i = 0; i < str_array.length; i++) {
                   //str_array[i] = str_array[i].replace(/^\s*/, "").replace(/\s*$/, "");
                   $('#id_uc').append($('<option>', str_array[i]).text(str_array[i]))
                   //alert(str_array[i]);
                }

            }
    });
}



    $("#id_dist").change(function () {
        update_meta_feedback_district()

    });
     $("#id_taluka").change(function () {
            update_meta_feedback_taluka()
    });




</script>
{% endblock %}
     </div>


{% endblock content %}